### ISSUE TITLE
UI 希望能更隐蔽点，提供命令行风格的 UI

### ISSUE THREAD

**Issue by miyouzi** [takayama-lily/vscode-qq#1]
白色无法调整大小的输入框，白色的气泡看起来还是挺显眼的。

希望能提供命令行风格的聊天 UI，图片逻辑保持不变，鼠标悬停显示缩略图

类似：
-  mojoqq
![image](https://user-images.githubusercontent.com/24269465/112924266-65fed280-9142-11eb-9399-7084242d31b7.png)

 - Telegram-CLI
![image](https://user-images.githubusercontent.com/24269465/112924423-ae1df500-9142-11eb-809c-6bec1074008e.png)

**Comment by takayama-lily** [comment]
会考虑的

**Comment by miyouzi** [comment]
```添加一枚console风格的主题``` 更新日志看到这个，请问如何启用 console 风格？我是需要手动下载或复制链接 https://github.com/takayama-lily/vscode-qq/tree/master/assets/console-theme 里的文件，然后 ```在@设置中加入theme_css和theme_js参数来设置它们的路径``` 吗 ？

**Comment by miyouzi** [comment]
感谢大佬实现，另外如果大佬有空的话，还是希望能吧默认模式的 [图片] 鼠标悬停显示缩略图的功能带到命令行模式

**Comment by sysnapse** [comment]
> 感谢大佬实现，另外如果大佬有空的话，还是希望能吧默认模式的 [图片] 鼠标悬停显示缩略图的功能带到命令行模式

我改良了一下命令行風格的主題，你可以試試看
https://github.com/sysnapse/vscode-qq-console-theme

**Comment by miyouzi** [comment]
> > 感谢大佬实现，另外如果大佬有空的话，还是希望能吧默认模式的 [图片] 鼠标悬停显示缩略图的功能带到命令行模式
> 
> 我改良了一下命令行風格的主題，你可以試試看 https://github.com/sysnapse/vscode-qq-console-theme

@sysnapse 这个主题好评！另外想问下回车发送消息而不是Ctrl+回车可以实现吗？

**Comment by sysnapse** [comment]
> > > 感谢大佬实现，另外如果大佬有空的话，还是希望能吧默认模式的 [图片] 鼠标悬停显示缩略图的功能带到命令行模式
> > 
> > 
> > 我改良了一下命令行風格的主題，你可以試試看 https://github.com/sysnapse/vscode-qq-console-theme
> 
> @sysnapse 这个主题好评！另外想问下回车发送消息而不是Ctrl+回车可以实现吗？

我记得我之前有改过，但是因为某些原因就继续用ctrl+回车了

**Comment by sysnapse** [comment]
> > > 感谢大佬实现，另外如果大佬有空的话，还是希望能吧默认模式的 [图片] 鼠标悬停显示缩略图的功能带到命令行模式
> > 
> > 
> > 我改良了一下命令行風格的主題，你可以試試看 https://github.com/sysnapse/vscode-qq-console-theme
> 
> @sysnapse 这个主题好评！另外想问下回车发送消息而不是Ctrl+回车可以实现吗？

更新了，現在應該可以回車直接發送
