### ISSUE TITLE
我该怎么填写 css 和 style 的本地链接

### ISSUE THREAD

**Issue by Stapxs** [takayama-lily/vscode-qq#12]
直接填写地址资源 404 了

![image](https://user-images.githubusercontent.com/42486439/118572730-adedbd80-b7b3-11eb-9809-69af23fb1ce6.png)
![image](https://user-images.githubusercontent.com/42486439/118572777-c8c03200-b7b3-11eb-999f-8a1980281f2b.png)

**Comment by takayama-lily** [comment]
此功能目前有点问题，css和js文件必须放在当前打开的项目目录（即当前workspace）下。
