### ISSUE TITLE
[禁止登录]当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。

### ISSUE THREAD

**Issue by PlayerYao** [takayama-lily/vscode-qq#13]
已知情况:
- Windows 10专业版
- 联想笔记本
- 两个QQ账号均登陆不上
- Clash挂代理(tun模式)/公司Wifi直连(关闭clash后重启电脑)
- 没有开启设备锁
- 电脑QQ没有在线
- 设置里设置登陆方式是安卓设备

**都提示上网环境异常,登陆不上**

**Comment by 913883232** [comment]
解决了吗？我也出现这个问题了

**Comment by takayama-lily** [comment]
应该是没有完成滑动验证码导致的。
你们是否有安装chrome，弹出滑动验证码后完成拉动？

**Comment by 913883232** [comment]
> 应该是没有完成滑动验证码导致的。
> 你们是否有安装chrome，弹出滑动验证码后完成拉动？

有自动打开chrome，然后也完成了滑动验证码

**Comment by takayama-lily** [comment]
这种情况比较少见，可能是登录所在IP有问题。
可以尝试换网络环境，成功后再换回来应该能解决。

**Comment by 913883232** [comment]
行吧，谢谢~

**Comment by CrazyJhq** [comment]
我也遇到了这个问题，请问楼主解决了吗？

**Comment by takayama-lily** [comment]
https://github.com/takayama-lily/vscode-qq/issues/13#issuecomment-842789688 解决方法参考

**Comment by PlayerYao** [comment]
> 这种情况比较少见，可能是登录所在IP有问题（公共网络，使用人数过多导致）。
> 
> **解决方法：**
> 
> * 打开设备锁（很重要）
> * 在家中电脑或安全的网络环境下登录一次vscode-qq
> * 之后在任何IP应该都可以使用vscode-qq登录此账号

在家中另外一台电脑上尝试
1. QQ大号(之前登录失败的帐号)登录不成功,依然报上网环境异常
2. 大号开启登陆保护后依然无法登录(上网环境异常)
3. 切换小号尝试(小号在公司也无法正常登录)没有启用登陆保护,可以在家中电脑正常登录
4. 此时再次尝试切换大号,依旧无法登录(关闭登陆保护)

**Comment by dawn-lc** [comment]
[](https://github.com/takayama-lily/oicq/issues/86)

**Comment by takayama-lily** [comment]
https://github.com/takayama-lily/vscode-qq/wiki/%5B%E7%A6%81%E6%AD%A2%E7%99%BB%E5%BD%95%5D%E5%BD%93%E5%89%8D%E4%B8%8A%E7%BD%91%E7%8E%AF%E5%A2%83%E5%BC%82%E5%B8%B8
