### ISSUE TITLE
QQ版本过低

### ISSUE THREAD

**Issue by ziyangcommon** [takayama-lily/vscode-qq#15]
![QQ拼音截图未命名](https://user-images.githubusercontent.com/9876231/121452542-30902400-c9d2-11eb-9102-a2280ae0e1c5.png)

**Comment by takayama-lily** [comment]
从未遇到过此问题，也无法复现，希望提供更多信息。
* 是否修改过`@设置`内的 `platform` ？
* 是在哪一步遇到的，是否完成了滑动验证码以及登录保护验证？
* 是大号还是新注册的小号，若是小号注册时间大概多久？
* 其他信息也可以提供一下：插件版本，vscode版本，你的操作系统

**Comment by Cloud370** [comment]
这种情况一般是QQ没开设备锁和没有绑定手机，开下设备锁就好了。

**Comment by takayama-lily** [comment]
可尝试使用扫码登录

**Comment by ErickJian22** [comment]
请问现在还可以用吗？现在版本是9.9.16
