### ISSUE TITLE
请问无法显示头像是什么原因呢？

### ISSUE THREAD

**Issue by chen244** [takayama-lily/vscode-qq#5]
![截图_选择区域_20210425224113](https://user-images.githubusercontent.com/60290287/115997899-6a21f100-a617-11eb-8a03-b6290fed8de0.png)

**Comment by takayama-lily** [comment]
拖头像到输入框中，能看到链接，访问该链接是否能看到头像？

**Comment by chen244** [comment]
> 拖头像到输入框中，能看到链接，访问该链接是否能看到头像？

拖动不了

**Comment by takayama-lily** [comment]
可能是`http`的问题，目前已全部使用`https`协议。
有空的时候望更新一下插件并告知我是否该问题解决了。

**Comment by chen244** [comment]
> 可能是`http`的问题，目前图片链接已全部使用`https`协议。
> 有空的时候望更新一下插件并告知我是否该问题解决了。

解决了
![截图_选择区域_20210427085824](https://user-images.githubusercontent.com/60290287/116169209-c7f92a80-a736-11eb-980e-16ade94657cf.png)
不过这底下的图标怎么会显示成这样呢？

**Comment by takayama-lily** [comment]
> 解决了
> ![截图_选择区域_20210427085824](https://user-images.githubusercontent.com/60290287/116169209-c7f92a80-a736-11eb-980e-16ade94657cf.png)
> 不过这底下的图标怎么会显示成这样呢？

与操作系统有关。你的操作系统是？

**Comment by chen244** [comment]
> > 解决了
> > ![截图_选择区域_20210427085824](https://user-images.githubusercontent.com/60290287/116169209-c7f92a80-a736-11eb-980e-16ade94657cf.png)
> > 不过这底下的图标怎么会显示成这样呢？
> 
> 与操作系统有关。你的操作系统是？

deepin..是字体有关吗？还是和字符集有关
