### ISSUE TITLE
接收文件有Bug，且希望增加传输文件功能

### ISSUE THREAD

**Issue by IcyFeather233** [takayama-lily/vscode-qq#55]
能收到别人发的文件，但是无法正常下载，下载下来的和传上去的不是一个东西

如图：
这个是收到的界面，点击可以下载
![image](https://user-images.githubusercontent.com/56245435/147848042-c7ed9d58-a0e2-45b9-bf54-76fe1582738a.png)

这是我下载到的文件：
![image](https://user-images.githubusercontent.com/56245435/147848064-bd8db9b6-cb0d-4a86-a2a1-0d01d6c461cd.png)
![image](https://user-images.githubusercontent.com/56245435/147848068-3b791398-8cef-4c71-bc7f-33e6815fae7e.png)

**Comment by ShellWen** [comment]
文件内容是对的，自己改下文件名，顺手 close 一下，谢谢
