### ISSUE TITLE
图片发送

### ISSUE THREAD

**Issue by HUGHNew** [takayama-lily/vscode-qq#8]
能否在wiki或者readme具体写一个案例呢 尝试了几次 没有发送图片成功

**Comment by takayama-lily** [comment]
`[CQ:image,file=C:/abc.jpg]` 或者
`[CQ:image,file=http://domain.com/abc.jpg]`

**Comment by HUGHNew** [comment]
提示为 `Error: empty message`  路径为`C:/User/HASEE/Desktop/vsc,jpg` 
但改成反斜杠后 提示 **Error: 群消息可能发送失败，请检查消息内容。** 这个应该是网络问题 但发送成功了
试了一下D盘 路径为 `D:/vsc.jpg` 发送成功了
是不是 C盘下可能有bug？

**Comment by HUGHNew** [comment]
提示为 `Error: empty message`  路径为`C:/User/HASEE/Desktop/vsc,jpg` 
但改成反斜杠后 提示 **Error: 群消息可能发送失败，请检查消息内容。** 这个应该是网络问题 但发送成功了
试了一下D盘 路径为 `D:/vsc.jpg` 发送成功了
是不是 C盘下可能有bug？

**Comment by takayama-lily** [comment]
应该是文件不存在或者你没有该文件的读取权限。
另外 `群消息可能发送失败，请检查消息内容。` 这个信息是偶尔出现，还是每次都出现？

**Comment by chenyuxi2002** [comment]
> `[CQ:image,file=C:/abc.jpg]` 或者
> `[CQ:image,file=http://domain.com/abc.jpg]`

另外关于图片发送我还发现了一个问题

当文件名中带有` ] `符号，会解析错误，导致此字符后面的部分文件名被截断，例如文件名：`example].jpg`。

这个文件名处理部分的代码我没有在源码中找到，是在服务端处理的吗？（后端仔，代码看的不是很懂）

**Comment by takayama-lily** [comment]
@chenyuxi2002 可以使用转义符：
[ = `&#91;`
] = `&#93;`
, = `&#44;`
& = `&amp;`

**Comment by HUGHNew** [comment]
哦哦 懂了
